/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Line b = new Line(new int[] { 2, 0 }, new int[] { 5, 10 }, 0, 1);

        Scanner scanner = new Scanner(System.in);

        int tickness = 0;

        do {
            System.out.println("Entre com a espessura da linha: ");
            tickness = scanner.nextInt();
        } while (tickness < Line.MAX_TICKNESS && tickness > Line.MIN_TICKNESS);

        Line a = new Line(new int[] { 0, 0 }, new int[] { 10, 10 }, 0, tickness);

        scanner.close();

        // -----------

        Person julia = new Person("Julia");
        Person maria = new Person("Maria");

        ArrayList<String> stringList = new ArrayList<>();
        LinkedList<Person> personList = new LinkedList<>();

        stringList.add("Hello");
        stringList.add("World");

        for (String string : stringList) {
            System.out.println(string);
        }

        personList.add(julia);
        personList.add(maria);

        personList.forEach(p -> System.out.println(p));

        stringList.forEach(System.out::println);

        boolean listContainsPoo = stringList.contains("POO");
        boolean listContainsHello = stringList.contains("Hello");

        stringList.remove("Hello");
        stringList.removeIf(s -> s.equals("World"));
    }
}
