/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import static org.fusesource.jansi.Ansi.Color.*;

public class App {
    public static void main(String[] args) throws Exception {
        var bar = new ProgressBar(15, '%', GREEN);

        bar.iniciar(true, "teste.txt", 100);
    }
}
